version: '3'
services:
  web:
    build: #Dockerfile in current directory
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - ".:/app" #current folder outside the container to the folder inside container
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - ".:/app"
    command: [ "npm","run","test" ]
